version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: saas-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      # Esta será la base de datos por defecto, pero crearemos las otras
      POSTGRES_DB: postgres 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Script para crear múltiples bases de datos
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: saas-dynamo
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

volumes:
  postgres_data: